### ISSUE TITLE
Build apk(android) error 

### ISSUE THREAD

**Issue by wangjacsi** [NilsBacke/PHSpeechBubble#19] opened 2020-04-28 00:52 UTC
When I run 'flutter build apk' in terminal, I got the error like this :

<img width="1867" alt="스크린샷 2020-04-28 오전 9 48 05" src="https://user-images.githubusercontent.com/5095201/80434865-ebc43d80-8935-11ea-842b-802893cc93b1.png">

How can I solve this problem?

**Comment by shinriyo** [comment] 2020-04-28 07:45
@wangjacsi 
안녕하십니까?
I guess that It caused by your `android/app/build.gradle` and the plugin's version are different 

`compileSdkVersion 28`

However, the pull-request was not merged yet. It may help you happy.
https://github.com/NilsBacke/PHSpeechBubble/pull/17/files

@NilsBacke Hello. Do you still maintain the plugin?

**Comment by shinriyo** [comment] 2020-09-30 23:03
@NilsBacke
hey

**Comment by NilsBacke** [comment] 2020-10-01 00:21
Sorry this was neglected for so long. I am barely maintaining this package anymore. Thank you for tagging me.

**Closed as completed by NilsBacke** 2020-10-01 00:21 UTC

**Comment by shinriyo** [comment] 2020-10-01 08:08
@NilsBacke 
Thank you
